// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGaDZlXp2-WuyPXpydmSHQSuw83kZ5Vkw',
    appId: '1:109163523055:web:5c9593f1af1be95a51e41a',
    messagingSenderId: '109163523055',
    projectId: 'health-monitor-system-c581d',
    authDomain: 'health-monitor-system-c581d.firebaseapp.com',
    storageBucket: 'health-monitor-system-c581d.appspot.com',
    measurementId: 'G-HZZBXJ1JJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJUy9CWgv6cztxnm6iOp_Z3jIxVBLkwMA',
    appId: '1:109163523055:android:bdc1fd8bbd4340e151e41a',
    messagingSenderId: '109163523055',
    projectId: 'health-monitor-system-c581d',
    storageBucket: 'health-monitor-system-c581d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp6aG78IVLjaFpFsnRVdrglUR7ZOP7-Gg',
    appId: '1:109163523055:ios:8769ff9d2bd196ca51e41a',
    messagingSenderId: '109163523055',
    projectId: 'health-monitor-system-c581d',
    storageBucket: 'health-monitor-system-c581d.appspot.com',
    iosClientId: '109163523055-g26elukfks2c2o24gr2cg8ekph0l8gl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthMonitorSystem1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp6aG78IVLjaFpFsnRVdrglUR7ZOP7-Gg',
    appId: '1:109163523055:ios:8769ff9d2bd196ca51e41a',
    messagingSenderId: '109163523055',
    projectId: 'health-monitor-system-c581d',
    storageBucket: 'health-monitor-system-c581d.appspot.com',
    iosClientId: '109163523055-g26elukfks2c2o24gr2cg8ekph0l8gl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthMonitorSystem1',
  );
}
